version: '3.8'

services:
  db-local-dev:
    ports: 
      - '${LOCAL_DEV_DB_PORT:-5432}:5432'
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=tasks_api_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  db-local-test:
    ports: 
      - '${LOCAL_TEST_DB_PORT:-5433}:5432'
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=tasks_api_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql