service: tasks-api

plugins:
  - serverless-offline
  - serverless-plugin-typescript-express

provider:
  name: aws
  runtime: nodejs14.x

functions:
  main:
    handler: src/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'